name: chainq_spellbook
version: 0.0.0
config-version: 2

profile: chainq

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chainq_spellbook:
    dex:
      +materialized: view
    erc20:
      +materialized: view
    filecoin:
      +materialized: view
    solana:
      +materialized: view
    prices:
      +materialized: view
    labels:
      +materialized: view
    nft:
      +materialized: view
    lending:
      +materialized: view
    bridge:
      +materialized: view
    live:
      +materialized: view
    whuffie:
      +materialized: view
