/**
 * `chainq init` — scaffold a new chainq workspace.
 *
 * Creates the directory layout, a starter config, a sample metric, and a
 * README pointing at the most common next steps. Designed to be safe to
 * re-run: existing files are skipped unless `force` is set.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface InitOptions {
  /** Absolute or relative path to initialise. */
  targetDir: string;
  /** When true, overwrite existing files. Otherwise skip them and log. */
  force?: boolean;
}

export interface InitResult {
  targetDir: string;
  created: string[];
  skipped: string[];
}

/**
 * Inline fallback for the starter metric. Used when the repo's bundled
 * `dex_volume_usd.yml` cannot be read (e.g. running from a published tarball
 * that doesn't ship the semantic package layout).
 */
const FALLBACK_SAMPLE_METRIC = `metric: dex_volume_usd
description: |
  DEX swap volume in USD across all supported aggregators.
  Aggregates \`dex.trades.amount_usd\`.
dimensions:
  - chain
  - dex_name
  - day
filters:
  - chain
  - dex_name
sql_template: |
  SELECT
    {{select_dimensions}},
    SUM(amount_usd) AS volume_usd
  FROM "dex.trades"
  WHERE block_time BETWEEN {{start}} AND {{end}}
    {{chain_clause}}
    {{dex_name_clause}}
  GROUP BY {{group_dimensions}}
  ORDER BY {{group_dimensions}}
dimension_expressions:
  chain: chain
  dex_name: dex_name
  day: "date_trunc('day', block_time)"
guardrails:
  max_range_days: 90
  max_rows: 50000
  timeout_seconds: 20
`;

const CONFIG_CONTENT = `${JSON.stringify(
  {
    version: "0.0.0",
    dataDir: "./data",
    metricsDir: "./metrics",
    outDir: "./out",
    engine: "duckdb",
  },
  null,
  2,
)}\n`;

const README_CONTENT = `# My chainq workspace

This directory was generated by \`chainq init\`.

- \`data/\` — Parquet files. Drop snapshots here.
- \`metrics/\` — YAML metric definitions consumed by the MCP server.
- \`out/\` — Generated charts and reports.
- \`chainq.config.json\` — Workspace config.

## Next steps

1. Seed sample data:
   \`\`\`
   chainq seed
   \`\`\`
2. Or pull a real snapshot (no RPC required):
   \`\`\`
   chainq pull --chain base --from 12000000 --to 12001000
   \`\`\`
3. Start the MCP server:
   \`\`\`
   chainq mcp serve --stdio
   \`\`\`
`;

function packageRoot(): string {
  // init.ts lives at <root>/packages/cli/src/init.ts, so three "..":
  //   src → cli → packages → <root>.
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, "..", "..", "..");
}

function loadSampleMetric(): string {
  try {
    const root = packageRoot();
    const metricPath = resolve(
      root,
      "packages/semantic/metrics/dex_volume_usd.yml",
    );
    return readFileSync(metricPath, "utf8");
  } catch {
    return FALLBACK_SAMPLE_METRIC;
  }
}

function ensureDir(path: string): void {
  mkdirSync(path, { recursive: true });
}

function writeFile(
  path: string,
  contents: string,
  force: boolean,
  created: string[],
  skipped: string[],
): void {
  if (existsSync(path) && !force) {
    skipped.push(path);
    return;
  }
  ensureDir(dirname(path));
  writeFileSync(path, contents);
  created.push(path);
}

export async function runInit(opts: InitOptions): Promise<InitResult> {
  const targetDir = resolve(opts.targetDir);
  const force = opts.force === true;

  ensureDir(targetDir);

  const dataDir = join(targetDir, "data");
  const metricsDir = join(targetDir, "metrics");
  const outDir = join(targetDir, "out");
  ensureDir(dataDir);
  ensureDir(metricsDir);
  ensureDir(outDir);

  const created: string[] = [];
  const skipped: string[] = [];

  writeFile(join(dataDir, ".gitkeep"), "", force, created, skipped);
  writeFile(
    join(targetDir, "chainq.config.json"),
    CONFIG_CONTENT,
    force,
    created,
    skipped,
  );
  writeFile(
    join(metricsDir, "sample_dex_volume.yml"),
    loadSampleMetric(),
    force,
    created,
    skipped,
  );
  writeFile(
    join(targetDir, "README.md"),
    README_CONTENT,
    force,
    created,
    skipped,
  );

  return { targetDir, created, skipped };
}
