#!/usr/bin/env tsx
/**
 * MCP end-to-end smoke test. Spawns the server as a child process, connects
 * an MCP client over stdio, asserts every tool is available, and exercises
 * the new metric / chart / report / recall surface.
 */

import { resolve } from "node:path";
import assert from "node:assert/strict";
import { existsSync, rmSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

async function main() {
  const dataDir = resolve("data");
  const cliEntry = resolve("packages/cli/src/bin.ts");

  // Reset cache so counts are deterministic.
  const cacheFile = resolve(dataDir, ".chainq-cache.duckdb");
  if (existsSync(cacheFile)) rmSync(cacheFile, { force: true });

  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [resolve("node_modules/tsx/dist/cli.mjs"), cliEntry, "mcp", "serve"],
    env: { ...process.env, CHAINQ_DATA_DIR: dataDir },
  });

  const client = new Client({ name: "chainq-smoke", version: "0.0.0" });
  await client.connect(transport);

  const tools = await client.listTools();
  const toolNames = tools.tools.map((t) => t.name).sort();
  console.log("[mcp-smoke] tools:", toolNames.join(", "));
  const expected = [
    "chainq_chart_render",
    "chainq_describe",
    "chainq_estimate_cost",
    "chainq_list_metrics",
    "chainq_list_tables",
    "chainq_metric",
    "chainq_query",
    "chainq_recall",
    "chainq_recall_by_id",
    "chainq_report",
    "chainq_search_tables",
  ];
  for (const name of expected) {
    assert.ok(toolNames.includes(name), `tool ${name} missing`);
  }

  const queryRes = await client.callTool({
    name: "chainq_query",
    arguments: {
      sql: `SELECT chain, COUNT(*) AS n FROM "dex.trades" GROUP BY chain ORDER BY chain`,
      label: "smoke:trades-by-chain",
    },
  });
  const queryJson = parseText(queryRes);
  assert.equal(queryJson.actualRows, 5);
  console.log("[mcp-smoke] query ok");

  const metrics = await client.callTool({ name: "chainq_list_metrics", arguments: {} });
  const metricsJson = parseText(metrics) as Array<{ metric: string }>;
  assert.ok(metricsJson.find((m) => m.metric === "dex_volume_usd"));
  console.log("[mcp-smoke] list_metrics ok");

  const metricRes = await client.callTool({
    name: "chainq_metric",
    arguments: {
      metric: "dex_volume_usd",
      dimensions: ["chain"],
      start: "2026-01-01 00:00:00",
      end: "2026-01-02 00:00:00",
    },
  });
  assert.ok(parseText(metricRes).result.actualRows >= 1);
  console.log("[mcp-smoke] metric ok");

  const recallRes = await client.callTool({
    name: "chainq_recall",
    arguments: { query: "trades-by-chain" },
  });
  const recallJson = parseText(recallRes) as Array<unknown>;
  assert.ok(recallJson.length >= 1, "recall should match the labelled query");
  console.log("[mcp-smoke] recall ok");

  const chartRes = await client.callTool({
    name: "chainq_chart_render",
    arguments: {
      type: "bar",
      data: [
        { chain: "ethereum", n: 2000 },
        { chain: "base", n: 2000 },
      ],
      x: "chain",
      y: "n",
      title: "smoke",
      filename: "smoke-bar.svg",
    },
  });
  const chartJson = parseText(chartRes);
  assert.ok(existsSync(chartJson.path), "chart svg missing");
  console.log(`[mcp-smoke] chart_render → ${chartJson.path}`);

  const reportRes = await client.callTool({
    name: "chainq_report",
    arguments: {
      title: "Smoke Report",
      filename: "smoke.html",
      summary: "Generated by mcp-smoke-test.",
      sections: [
        { heading: "Trades", table: [{ chain: "ethereum", n: 2000 }] },
        { heading: "Chart", chartPath: chartJson.path },
      ],
    },
  });
  const reportJson = parseText(reportRes);
  assert.ok(existsSync(reportJson.path), "report file missing");
  assert.equal(reportJson.format, "html", "expected html format by default");
  console.log(`[mcp-smoke] report → ${reportJson.path}`);

  await client.close();
  console.log("[mcp-smoke] ok");
}

function parseText(result: { content: Array<{ type: string; text?: string }> }): any {
  const text = result.content.find((c) => c.type === "text")?.text;
  if (!text) throw new Error("no text in tool result");
  return JSON.parse(text);
}

main().catch((err) => {
  console.error("[mcp-smoke] FAILED:", err);
  process.exit(1);
});
